### ISSUE TITLE
Slots that are more than quarter-full look empty

### ISSUE THREAD

**Issue by belathus** [BrassGoggledCoders/NetherBarrels#1]
In the following screenshot, the barrel shown is completely full, as evidenced by the 15 strength redstone signal coming from the comparator. However if you open the barrel, it looks as if it were completely empty. It isn't, but it does look like it is.

Looking at it closer, it does appear that the items in the slot "vanish" when the stack contains more than 127 items. However, the items reappear when more than 256 items (though, the size of the stack is displayed wrong; having 268 items in the slot is shown as 2 items). Then the stack disappears once it reaches 384 items (when the stack size would be displayed at 128 again).

![2022-06-29_03 08 14](https://user-images.githubusercontent.com/3826783/176373989-512acc2e-4b0d-47d9-8c6e-8e217980d87f.png)
![2022-06-29_03 08 27](https://user-images.githubusercontent.com/3826783/176374287-834d25e4-296d-427b-880c-294e94e271ee.png)
![2022-06-29_03 17 28](https://user-images.githubusercontent.com/3826783/176375596-f3fd41f4-9de2-44d6-8f60-293ea56fdb44.png)

**Comment by SkySom** [comment]
Fixed.
